M48
; DRILL file KiCad 10.0.1 date 2026-04-23T16:51:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-23T16:51:36+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.700
%
G90
G05
T1
X224.485Y-52.51
X224.485Y-58.29
T2
X141.8Y-26.2
X149.8Y-26.2
T3
X131.5Y-85.4
X131.6Y-75.4
X138.5Y-85.4
X138.6Y-75.4
T4
X132.8Y-105.1
X132.9Y-28.0
X226.4Y-28.0
X226.4Y-105.1
M30
